name: Run Python Script with Conda Environment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    # Step 1: Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Miniconda
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.9  # Specify Python version
        auto-activate-base: false  # Avoid activating the base Conda environment

    # Step 3: Initialize Conda and Create Environment
    - name: Initialize Conda and Create Environment
      run: |
        # Initialize Conda for the current shell session
        conda init bash
        # Reload shell configuration to apply Conda initialization
        source ~/.bashrc
        # Create Conda environment
        conda create --name myenv python=3.9 -y
        # Activate environment and install dependencies
        conda activate myenv
        conda install -c conda-forge geopandas requests -y
        # Persist environment activation for subsequent steps
        echo "conda activate myenv" >> $GITHUB_ENV

    # Step 4: Run Python script
    - name: Run Python script
      run: |
        # Activate the Conda environment and run the script
        conda activate myenv
        python main.py
